# Generated by Django 4.1.5 on 2023-05-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_orderitem_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('P', 'Phones'), ('T', 'Tablets'), ('C', 'Computers'), ('M', 'Monitors')], max_length=2),
        ),
    ]
